Repository InFlammis/BHJ2022, pull requests merged in 2022-04, with the labels that each got.

#15 Upload graphics
  Artwork/Spritesheet eye.png
  Artwork/Spritesheet scribble.png
  Artwork/Spritesheet squiggle.png
  Artwork/Spritesheet triangle.png
  Artwork/eye.kra
  Artwork/scribble.kra
  Artwork/squiggle.kra
  Artwork/triangle.kra
Labels: animations, graphics

#32 All enemies can now be killed
  Assets/Prefabs/Enemies/Eye/Eye.prefab
  Assets/Prefabs/Enemies/Eye/Settings/Eye Init Settings.asset
  Assets/Prefabs/Enemies/Squiggle/Squiggle.prefab
  Assets/Prefabs/Enemies/Triangle/Settings/Triangle Init Settings.asset
  Assets/Prefabs/Enemies/Triangle/Triangle.prefab
  Assets/Scenes/Levels/Level_01.unity
  Assets/Scripts/Enemies/Eye/EyeControllerCore.cs
  Assets/Scripts/Enemies/Scribble/ScribbleControllerCore.cs
  Assets/Scripts/Enemies/Squiggle/SquiggleControllerCore.cs
  Assets/Scripts/Enemies/Triangle/TriangleControllerCore.cs
Labels: enemies, bug-fix

#33 Orchestration's CancellationToken checked on Orchestration cancellation
  Assets/Scripts/Managers/OrchestrationManagement/OrchestrationManager.cs
Labels: bug-fix

#35 Settings extracted from Managers
  Assets/Prefabs/Managers/Log Manager.meta
  Assets/Prefabs/Managers/Log Manager/LogManager Settings.asset
  Assets/Prefabs/Managers/Log Manager/LogManager Settings.asset.meta
  Assets/Prefabs/Managers/Log Manager/Logger.prefab
  Assets/Prefabs/Managers/Log Manager/Logger.prefab.meta
  Assets/Prefabs/Managers/Orchestration Manager.meta
  Assets/Prefabs/Managers/Orchestration Manager/OrchestrationManager Settings.asset
  Assets/Prefabs/Managers/Orchestration Manager/OrchestrationManager Settings.asset.meta
  Assets/Prefabs/Managers/Orchestration Manager/OrchestrationManager.prefab
  Assets/Prefabs/Managers/Orchestration Manager/OrchestrationManager.prefab.meta
  Assets/Prefabs/Managers/Sound Manager.meta
  Assets/Prefabs/Managers/Sound Manager/SoundManager Settings.asset
  Assets/Prefabs/Managers/Sound Manager/SoundManager Settings.asset.meta
  Assets/Prefabs/Managers/Sound Manager/SoundManager.prefab
  Assets/Prefabs/Managers/Sound Manager/SoundManager.prefab.meta
  Assets/Scripts/Enemies/EnemySettings.cs
  Assets/Scripts/Enemies/EnemySoundSettingsSO.cs
  Assets/Scripts/Managers/HealthManagement/HealthManagerSettingsSO.cs
  Assets/Scripts/Managers/Levels/LevelSceneSoundSettingsSO.cs
  Assets/Scripts/Managers/LogManagement/LogManager.cs
  Assets/Scripts/Managers/LogManagement/LogManager.cs.meta
  Assets/Scripts/Managers/LogManagement/LogManagerSettingsSO.cs
  Assets/Scripts/Managers/LogManagement/LogManagerSettingsSO.cs.meta
  Assets/Scripts/Managers/Menus/MenuSceneSoundSettingsSO.cs
  Assets/Scripts/Managers/OrchestrationManagement/OrchestrationManager.cs
  Assets/Scripts/Managers/OrchestrationManagement/OrchestrationManagerSettingsSO.cs
  Assets/Scripts/Managers/OrchestrationManagement/OrchestrationManagerSettingsSO.cs.meta
  Assets/Scripts/Managers/SoundManagement/SoundManagerInitSettingsSO.cs
  Assets/Scripts/Player/PlayerSettings.cs
  Assets/Scripts/Player/PlayerSoundSettingsSO.cs
  Assets/Scripts/PowerUps/PowerUpSettings.cs
  Assets/Scripts/Weapons/BulletSettings.cs
  Assets/Scripts/Weapons/WeaponSettings.cs
Labels: enhancement, refactoring

#37 #18 fix startup warnings
  Assets/Prefabs/Managers/Orchestration Manager/OrchestrationManager Settings.asset
  Assets/Scenes/Menus/PauseMenu.unity
  Assets/Scripts/Managers/GameManagement/StateMachine/Init.cs
  Assets/Scripts/Managers/Levels/Level_01ManagerCore.cs
  Assets/Scripts/Managers/Levels/StateMachine/GameOver.cs
  Assets/Scripts/Managers/Levels/StateMachine/Play.cs
  Assets/Scripts/Managers/Levels/StateMachine/State.cs
  Assets/Scripts/Managers/Levels/StateMachine/WaitForStart.cs
  Assets/Scripts/Managers/Levels/StateMachine/Win.cs
  Assets/Scripts/Managers/LogManagement/LogManager.cs
  Assets/Scripts/Managers/Menus/Credits/CreditsMenuManager.cs
  Assets/Scripts/Managers/Menus/Credits/CreditsMenuManagerCore.cs
  Assets/Scripts/Managers/Menus/Credits/ICreditsMenuManager.cs
  Assets/Scripts/Managers/Menus/Help/HelpMenuManager.cs
  Assets/Scripts/Managers/Menus/Help/HelpMenuManagerCore.cs
  Assets/Scripts/Managers/Menus/Help/IHelpMenuManager.cs
  Assets/Scripts/Managers/Menus/Main/IMainMenuManager.cs
  Assets/Scripts/Managers/Menus/Main/MainMenuManager.cs
  Assets/Scripts/Managers/Menus/Main/MainMenuManagerCore.cs
  Assets/Scripts/Managers/Menus/Pause/IPauseMenuManager.cs
  Assets/Scripts/Managers/Menus/Pause/PauseMenuManager.cs
  Assets/Scripts/Managers/Menus/Pause/PauseMenuManagerCore.cs
  Assets/Scripts/MessageBroker/Events/ILevelStateMachineEvents.cs
  Assets/Scripts/MessageBroker/Events/ILevelStateMachineEvents.cs.meta
  Assets/Scripts/MessageBroker/Implementations/Messenger.LevelStateMachineEvents.cs
  Assets/Scripts/MessageBroker/Implementations/Messenger.LevelStateMachineEvents.cs.meta
  Assets/Tests/EditMode/Managers/GameManagement/StateMachine/InitUnitTests.cs
  Assets/Tests/EditMode/Managers/GameManagement/StateMachine/PauseUnitTests.cs
  Assets/Tests/EditMode/Managers/Menus/MainMenuManagerUnitTests.cs
  Assets/Tests/EditMode/Managers/Menus/PauseMenuManagerUnitTests.cs
  UserSettings/EditorUserSettings.asset
Labels: bug

#38 #36 control menu from gamepad
  Assets/Input/PlayerActionAsset.cs
  Assets/Input/PlayerActionAsset.inputactions
  Assets/Prefabs/Managers/Log Manager/LogManager Settings.asset
  Assets/Scenes/Menus/Button.prefab
  Assets/Scenes/Menus/CreditsMenu.unity
  Assets/Scenes/Menus/HelpMenu.unity
  Assets/Scenes/Menus/MainMenu.unity
  Assets/Scenes/Menus/PauseMenu.unity
  Assets/Scripts/Managers/GameManagement/StateMachine/Pause.cs
  Assets/Scripts/Managers/OrchestrationManagement/Wave.cs
  UserSettings/EditorUserSettings.asset
Labels: bug-fix

#51 #39 camera follows player
  Assets/Prefabs/Managers/Orchestration Manager/OrchestrationManager Settings.asset
  Assets/Scenes/Levels/Level_01.unity
  Assets/Scripts/Managers/CameraManagement.meta
  Assets/Scripts/Managers/CameraManagement/CameraManager.cs
  Assets/Scripts/Managers/CameraManagement/CameraManager.cs.meta
  Assets/Scripts/MessageBroker/Events/IPlayerEvents.cs
  Assets/Scripts/MessageBroker/Implementations/Messenger.PlayerEvents.cs
  Assets/Scripts/Player/PlayerController.cs
  Assets/Scripts/Player/PlayerControllerCore.cs
  UserSettings/EditorUserSettings.asset
Labels: enhancement, player

#54 #39 camera follows player
  Assets/Prefabs/Enemies/Eye/Animations/Eye.controller
  Assets/Scripts/Managers/CameraManagement/CameraManager.cs
Labels: enhancement, player

#59 #49 pause menu
  Artwork/Textures/Textures layout/background_seamless.png
  Assets/Quit Button Animation.anim
  Assets/Quit Button Animation.anim.meta
  Assets/Quit Current Button.controller
  Assets/Quit Current Button.controller.meta
  Assets/Scenes/Menus/Common/Materials.meta
  Assets/Scenes/Menus/Common/Materials/Menu Background.mat
  Assets/Scenes/Menus/Common/Materials/Menu Background.mat.meta
  Assets/Scenes/Menus/Common/Materials/background_seamless.png
  Assets/Scenes/Menus/Common/Materials/background_seamless.png.meta
  Assets/Scenes/Menus/Pause menu/Animations/Resume Button Animation.anim
  Assets/Scenes/Menus/Pause menu/Animations/Resume Button Animation.anim.meta
  Assets/Scenes/Menus/Pause menu/Animations/Resume button.controller
  Assets/Scenes/Menus/Pause menu/Animations/Resume button.controller.meta
  Assets/Scenes/Menus/Pause menu/Animations/Spritesheet quit current.png
  Assets/Scenes/Menus/Pause menu/Animations/Spritesheet quit current.png.meta
  Assets/Scenes/Menus/Pause menu/Animations/Spritesheet resume.png
  Assets/Scenes/Menus/Pause menu/Animations/Spritesheet resume.png.meta
  Assets/Scenes/Menus/Pause menu/PauseMenu.unity
  UserSettings/EditorUserSettings.asset
Labels: animations, ui

#60 #50 credits menu
  Assets/Fonts/Vic.meta
  Assets/Fonts/Vic/Vic-Regular SDF.asset
  Assets/Fonts/Vic/Vic-Regular SDF.asset.meta
  Assets/Fonts/Vic/Vic-Regular.ttf
  Assets/Fonts/Vic/Vic-Regular.ttf.meta
  Assets/Scenes/Menus/Credits menu/Animations/Spritesheet back.png
  Assets/Scenes/Menus/Credits menu/Animations/Spritesheet back.png.meta
  Assets/Scenes/Menus/Credits menu/Back Button.controller
  Assets/Scenes/Menus/Credits menu/Back Button.controller.meta
  Assets/Scenes/Menus/Credits menu/Back button animation.anim
  Assets/Scenes/Menus/Credits menu/Back button animation.anim.meta
  Assets/Scenes/Menus/Credits menu/CreditsMenu.unity
  Assets/Scenes/Menus/Pause menu/Animations/Resume button.controller
  UserSettings/EditorUserSettings.asset
Labels: animations, ui

#61 Help menu graphics replaced with new one
  Assets/Scenes/Menus/Help menu/HelpMenu.unity
  UserSettings/EditorUserSettings.asset
Labels: animations, ui
